- alias: Heal zwave nightly
  hide_entity: True
  trigger:
    platform: time
    after: '2:31:00'
  action:
    service: zwave.heal_network

- alias: Flush TTS Cache
  hide_entity: True
  trigger:
    platform: time
    after: '2:35:00'
  action:
    service: tts.clear_cache