homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Web UI configuration
http:
  api_password: !secret http_api_password
  cors_allowed_origins:
    - http://localhost:3000
  trusted_networks:
    - 10.5.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Enables the frontend
frontend:
# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Track the sun
sun:
# History Configuration
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
# View all events in a logbook
logbook:

###### Start Instance Configuration ######

# Recorder
recorder: !include recorder.yaml

# Openzwave configuration
zwave:
  usb_path: /dev/ttyACM0

# Nest configuration  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Default climate to nest
climate:
  platform: nest

# Media Player Configuration
media_player:
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 30
    show_all_controls: true
    use_episode_art: true
  - platform: roku

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Text to speech
tts:
  platform: google

# Alarm Panel Binary Sensor
envisalink:
  host: !secret envisalink_host
  panel_type: DSC
  user_name: !secret envisalink_user
  password: !secret envisalink_pwd
  code: !secret envisalink_code
  evl_version: 4
  zones:
    1:
      name: 'Front + Garage'
      type: 'opening'
    2:
      name: 'Patio Door'
      type: 'opening'
    3:
      name: 'Study + Dining'
      type: 'opening'
    4:
      name: 'Master'
      type: 'opening'
    5:
      name: 'Guest'
      type: 'opening'
    6:
      name: 'Upstairs'
      type: 'opening'
  partitions:
    1:
      name: 'State'

group: !include groups.yaml
sensor: !include_dir_merge_list sensor
