downstairs:
  name: 'Automations'
  view: yes
  entities:
    - group.all_automation
    - group.scenes
    
scenes:
  name: 'Scenes'
  entities:
    - scene.exterior_lights_on
    - scene.exterior_lights_off