# Triggers mud room light to turn on with motion
- alias: 'Mud Room - Turn on light on motion'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_multisensor_6_burglar
      state: 0
      from: 8
  condition:
    condition: state
    entity_id: sensor.aeotec_multisensor_6_luminance
    below: 50
  action:
    - service: switch.turn_on
      entity_id: switch.homeseer_hsws100_wall_switch_switch_8_0

# Triggers mud room light to turn off with no motion
- alias: 'Mud Room - Turn off light on motion'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_multisensor_6_burglar
      state: 8
      from: 0
  condition:
    condition: state
    entity_id: sensor.aeotec_multisensor_6_luminance
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.homeseer_hsws100_wall_switch_switch_8_0