# Triggers exterior lights off via sun & controlled by a scene
- alias: 'Mud Room - Turn on light on motion'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_multisensor_6_burglar
      state: '0'
      from: '8'

  condition:
    - platform:
      entity_id: sensor.aeotec_multisensor_6_luminance
      state: 50

  action:
    - service: light.turn_on
      entity_id: switch.homeseer_hsws100_wall_switch_switch_8_0