- alias: 'Mud Room - Turn on light on motion'
  trigger:
    platform: state
    entity_id: sensor.aeotec_multisensor_6_burglar
    from: '0'
    to: '8'
  condition:
    - platform: numeric_state
      entity_id: sensor.aeotec_multisensor_6_luminance
      # At least one of the following required
      below: 50
  action:
    service: light.turn_on
    entity_id: switch.homeseer_hsws100_wall_switch_switch_8_0