# Triggers office light to turn on with motion
- alias: 'Office - Turn on light on motion'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2
      to: '8'
      from: '0'
  condition:
    condition: numeric_state
    entity_id: sensor.aeotec_zw100_multisensor_6_luminance_2
    below: '20'
  action:
    - service: switch.turn_on
      entity_id: switch.homeseer_hsws100_wall_switch_switch_4

# Triggers officelight to turn off with no motion
- alias: 'Office - Turn off light on motion'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2
      to: '0'
      from: '8'
  condition:
    condition: state
    entity_id: switch.homeseer_hsws100_wall_switch_switch_4
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.homeseer_hsws100_wall_switch_switch_4